## NumPy practicals done from Fluidic Colours YouTube Channel.

In [1]:
import numpy as np

In [2]:
A = np.random.randint(0,10,(5,3))

In [3]:
A.max() # it will display maximum element

9

In [4]:
A.min() # it will display minimum element

0

In [5]:
A.max(axis=0) # to find maximum element in each row. axis=0 stands for row.

array([9, 8, 5])

In [6]:
A.min(axis=1) # to find minimum element in each column. axis=1 stands for column.

array([1, 3, 0, 2, 1])

In [7]:
B = A.flatten() # entire array elements are put in a row.

In [8]:
np.argmax(B) # Now, position of maximum element will be displayed by this function.

3

In [9]:
np.argmin(B) # it will display position of minimum element.

8

In [10]:
A.argmax(axis=0)

array([1, 2, 3], dtype=int64)

In [11]:
A.argmin(axis=1)

array([0, 2, 2, 1, 2], dtype=int64)

In [12]:
A.mean() # mean of all the element will be printed

4.2

In [13]:
A.sum() # it will print sum of all elements

63

In [14]:
A.mean(axis=0)

array([5.6, 4.8, 2.2])

In [15]:
A.mean(axis=1)

array([1.66666667, 6.33333333, 5.33333333, 4.66666667, 3.        ])

In [16]:
A.std() # standard deviation of all the elements put together will be diaplayed.

2.87981480886069

In [17]:
A.std(axis=0)

array([3.0724583 , 2.48193473, 1.72046505])

In [18]:
A.std(axis=1)

array([0.47140452, 2.49443826, 3.77123617, 2.05480467, 1.63299316])

In [19]:
A.var() # variance of all the elements will be displayed.

8.293333333333333

In [20]:
A.var(axis=0)

array([9.44, 6.16, 2.96])

In [21]:
A.var(axis=1)

array([ 0.22222222,  6.22222222, 14.22222222,  4.22222222,  2.66666667])

In [22]:
A.cumsum() # cumulative sum will be displayed

array([ 1,  3,  5, 14, 21, 24, 32, 40, 40, 47, 49, 54, 57, 62, 63],
      dtype=int32)

In [23]:
A.cumprod() # cumulative product

array([    1,     2,     4,    36,   252,   756,  6048, 48384,     0,
           0,     0,     0,     0,     0,     0], dtype=int32)

In [24]:
A_flat = A.flatten()

In [25]:
A_flat

array([1, 2, 2, 9, 7, 3, 8, 8, 0, 7, 2, 5, 3, 5, 1])

In [26]:
np.argsort(A_flat)

array([ 8,  0, 14,  1,  2, 10,  5, 12, 11, 13,  4,  9,  6,  7,  3],
      dtype=int64)

In [27]:
np.sort(A_flat)

array([0, 1, 1, 2, 2, 2, 3, 3, 5, 5, 7, 7, 8, 8, 9])