In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([10,11,12,13])

In [3]:
a+b

array([11, 13, 15, 17])

In [4]:
a-b

array([-9, -9, -9, -9])

In [5]:
a*b

array([10, 22, 36, 52])

In [6]:
a/b

array([0.1       , 0.18181818, 0.25      , 0.30769231])

In [7]:
a**b

array([       1,     2048,   531441, 67108864], dtype=int32)

In [8]:
print(np.__version__)

1.18.1


In [9]:
my_list = [-17, 0, 4, 5, 9]

In [10]:
my_array_from_list = np.array(my_list)

In [11]:
my_array_from_list

array([-17,   0,   4,   5,   9])

In [12]:
my_array_from_list*10

array([-170,    0,   40,   50,   90])

In [13]:
my_tuple = (14, -3.54, 5+7j)
np.array(my_tuple)

array([14.  +0.j, -3.54+0.j,  5.  +7.j])

One thing to notice here i.e. each of the element was converted into a complex number. In NumPy, all the elements of an array has to be of same type.

Difference between Python and NumPy data structure:- The important differences are in the ways tuple and arrays are promoted and then used in mathematical operations. An * operator will replicate the tuple in Python whereas in NumPy it will work as a multiplication operator.

In [14]:
np.array(my_tuple)*6

array([ 84.   +0.j, -21.24 +0.j,  30.  +42.j])

NumPy has useful inbuilt functions for creating arrays. One of them is arange function. Eg. arange(10, 23). Here 10 is start parameter and 23 is stop parameter. This function will make an array with start value 10 and will continue till 22.

In [15]:
np.arange(10,23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [16]:
np.arange(10,23) - 10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

This command subtracted 10 from every element of the array to be created and made an array of elements after subtraction.

In [17]:
np.arange(2,20)-10+1

array([-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10])

In [18]:
len(np.arange(23, 35))

12

In [19]:
my_range_array = np.arange(23,35)

In [20]:
my_range_array.size

12

In [21]:
np.arange(10,23,5)

array([10, 15, 20])

In [22]:
np.arange(10,27,-3)

array([], dtype=int32)

In [23]:
np.arange(10,27,3)

array([10, 13, 16, 19, 22, 25])

In [24]:
np.arange(26, step=5)

array([ 0,  5, 10, 15, 20, 25])

In [25]:
np.arange(0,26,step=5)

array([ 0,  5, 10, 15, 20, 25])

linspace() function creates a group of numbers that are linearly or evenly spaced over specified intervals. zeros() function creates an array where every element is set to 0 and ones() function creates an array where every element is set to 1. linspace and arange returns arrays by default and are filled with integers wheras zeros and ones return arrays with floating point values.

In [26]:
np.linspace(5,15,9)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [27]:
my_linspace = np.linspace(5,15,9,retstep=True)

In [28]:
my_linspace

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [29]:
my_linspace[1]

1.25

In [30]:
my_linspace[0]

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [33]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.zeros((5,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [35]:
np.zeros((5,4,3,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0

In [36]:
np.zeros(11, dtype = 'int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [37]:
my_vector = np.array([-17,-4,0,2,21,37,105])

In [38]:
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [39]:
my_vector[0]

-17

In [40]:
my_vector[0]=-102

In [41]:
my_vector

array([-102,   -4,    0,    2,   21,   37,  105])

In [42]:
my_vector[305%7]

21

In [43]:
my_vector[-3]

21

In [44]:
my_vector[305%my_vector.size]

21

It clearly indicates power of indexing both within Python and NumPy.

## 2-D Arrays:

In [45]:
my_array = np.arange(35)

In [46]:
my_array.shape=(7,5)

In [47]:
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [48]:
my_array[2]

array([10, 11, 12, 13, 14])

In [49]:
my_array[-2]

array([25, 26, 27, 28, 29])

In [50]:
my_array[4,4]

24

In [51]:
row=5
col=2
my_array[row,col]

27

In [52]:
my_array[row][col]

27

## Boolean Mask Arrays:

In [53]:
my_vector = np.array([-17,-4,0,2,21,37,105])

In [54]:
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [55]:
zero_mod_7_mask = 0 == (my_vector%7)

This command makes every element of my_vector divide by 7 and if completely divisible it prints True else False.

In [56]:
zero_mod_7_mask

array([False, False,  True, False,  True, False,  True])

In [57]:
sub_array = my_vector[zero_mod_7_mask]

In [58]:
sub_array

array([  0,  21, 105])

In [59]:
sub_array[sub_array>0]

array([ 21, 105])

In [60]:
sub_array

array([  0,  21, 105])

Here we can see that elements of sub_array did not change.