## NumPy practicals done from Acadgild YouTube Channel.

In [1]:
import numpy as np

## NumPy functions

In [2]:
np.eye(6)
# this will create an identity matrix. By identity matrix we mean the diagonal elements will be 1 and remaining 
# elements will be 0 (zero). All the elements will be of float datatype by default. Number of rows and columns
# will be 6 each.

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

np.diag(array_name) -- This function will simply extract the diagonal values of the array.

In [3]:
list(range(10)) # Out put will be a list.

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
print(np.arange(10, 30, 5))

[10 15 20 25]


In [5]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [6]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [7]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(np.tril(arr, -1))
# this will print triangular lower matrix. l stands for lower. If we not use -1, diagonal elements will
# also get printed.

[[0 0 0]
 [4 0 0]
 [7 8 0]]


In [9]:
np.triu([[1,2,3],[4,5,6],[7,8,9]], 1)
# Here, u stands for upper triangle. If we not use 1, diagonal elements will also get printed.

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [10]:
np.triu([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [11]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

If we try to reshape to (2,2,4), then we will get value error: 'Can not reshape an array of size 12 into shape (2,2,4)

In [12]:
s = np.array(['a', 'b', 'c', 'd'])

In [13]:
s.reshape(2,2)

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

## Random Number generation:

In [14]:
print("Random number generation (from uniform distribution)")
print(np.random.rand(2,3))

Random number generation (from uniform distribution)
[[0.28385284 0.01286277 0.0444358 ]
 [0.68446722 0.58815747 0.92726351]]


In [15]:
print("Numbers from Normal Distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal Distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.60855863 -0.41443038  0.27477496]
 [-0.08758772 -0.1109015  -1.01315152]
 [-2.20387687 -0.61398416  0.03036804]
 [-0.78248777  2.62855489  1.10570887]]


## Basic Operations:

In [16]:
a = np.array([20, 30, 40, 50])

In [17]:
b = np.arange(1,5)

In [18]:
add = a+b
print(add)

[21 32 43 54]


In [19]:
sub = a-b
print(sub)

[19 28 37 46]


In [20]:
div = a/b
print(div)

[20.         15.         13.33333333 12.5       ]


In [21]:
mul = a*b
print(mul)

[ 20  60 120 200]


Scalars are single values.

In [22]:
b**2

array([ 1,  4,  9, 16], dtype=int32)

In [23]:
b*10

array([10, 20, 30, 40])

In [24]:
a<35

array([ True,  True, False, False])

## Matrix Operations:

In [25]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])

In [26]:
add = A+B

In [27]:
sub = A-B

In [28]:
print(add)

[[3 1]
 [3 5]]


In [29]:
print(sub)

[[-1  1]
 [-3 -3]]


In [30]:
C = np.array([[2,3], [3,4], [3,4]])

In [31]:
D = np.array([[2,2], [3,4]])

In [32]:
C.dot(D)

array([[13, 16],
       [18, 22],
       [18, 22]])

We can also use np.dot(A,B).

In [33]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

Some operations such as += and *= act inplace to modify an existing arrayrather than create a new one.

In [34]:
A += B

In [35]:
print(A)

[[3 1]
 [3 5]]


In [36]:
A *= B

In [37]:
print(A)

[[ 6  0]
 [ 9 20]]


## Methods:
Let a be an array. Then:                                                                                              to calculate sum of elements we can use a.sum() function,                                                             to find minimum of elements we can use a.min() function,                                                              to find maximum of elements we can use a.max() function,                                                                to calculate mean of elements we use a.mean() function,                                                                  to calculate standard deviation we use a.std() function.

a.sum(axis=0): Through this, all elements of columns will be summed up and displayed.                                   
a.sum(axis=1): Through this, all elements of rows will be summed up and displayed.

## Universal Functions:
In NumPy, familiar mathematical functions such as sin, cos, exp, etc are called "Universal Functions" or ufuncs. These functions operate element wise on an array and produces an array as output.

Some of the universal functions are exp, sqrt, argmax, max, argmin, argsort, average, ceil, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, maximum, mean, median, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize. 

## Indexing, Slicing and Iterating:

In [38]:
A = np.arange(20).reshape(5,4)

In [39]:
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [40]:
# Now when we slice i.e.
A[2:4, 1:3]

array([[ 9, 10],
       [13, 14]])

In [41]:
A[0:3,1] # It will print each row in second column

array([1, 5, 9])

In [42]:
A[:,1] # it is equivalent to previous example i.e. all elements from axis 0.

array([ 1,  5,  9, 13, 17])

In [43]:
A[3, ...] # To be explored 

array([12, 13, 14, 15])

## Methods used for shape manipulation:
ravel, flat, reshape, resize, T(for transpose)

## Important attributes of ndarray object:

ndrray.ndim: the number of axes (dimensions) of array. The number of dimensions is referred to as rank.

ndarray.shape: this is a tuple of integers indicating the size of the array in each dimensions. For a matrix with n rows and m columns, shape will be (n,m).

ndarray.size: the total number of elements of the array. This is equal to the product of the elements of shape.

ndarray.dtype: an object decsribing the type of the elements.

## Data types in NumPy:
bool, int, intc, intp, int8, int16, int32, int64, uint8, uint16, uint32, float_, float16, float32, float64, complex_, 
complex64, complex128.

## Stacking together different arrays:

In [44]:
x = np.floor(10*np.random.random((2,2)))

In [45]:
print(x)

[[1. 2.]
 [2. 1.]]


In [46]:
y = np.floor(10*np.random.random((2,2)))

In [47]:
print(y)

[[2. 0.]
 [0. 6.]]


In [48]:
np.vstack((x,y))

array([[1., 2.],
       [2., 1.],
       [2., 0.],
       [0., 6.]])

In [49]:
np.hstack((x,y))

array([[1., 2., 2., 0.],
       [2., 1., 0., 6.]])

hstack and vstack helps in stacking more than 2-D arrays. For 1-D array column_stack is used. Concatenate is for multi-dimensional arrays where we can specify axis to concatenate.

In [50]:
np.concatenate((x,y), axis=1)

array([[1., 2., 2., 0.],
       [2., 1., 0., 6.]])

In [51]:
m = np.array([4.,3.])
n = np.array([6.,8.])

In [52]:
np.column_stack((m,n))

array([[4., 6.],
       [3., 8.]])

In [53]:
np.row_stack((m,n))

array([[4., 3.],
       [6., 8.]])

## Splitting an array into smaller ones:-

In [54]:
l = np.floor(10*np.random.random((4,12)))

In [55]:
np.hsplit(l,3) # it will split the array horizontally in 3 equal parts.

[array([[0., 0., 7., 9.],
        [2., 0., 2., 3.],
        [4., 8., 2., 8.],
        [2., 3., 2., 6.]]), array([[4., 8., 8., 5.],
        [4., 4., 9., 1.],
        [1., 6., 7., 2.],
        [1., 4., 5., 3.]]), array([[0., 7., 9., 5.],
        [8., 9., 3., 9.],
        [4., 9., 8., 4.],
        [2., 5., 9., 3.]])]

In [56]:
np.hsplit(l, (3,8,9))

[array([[0., 0., 7.],
        [2., 0., 2.],
        [4., 8., 2.],
        [2., 3., 2.]]), array([[9., 4., 8., 8., 5.],
        [3., 4., 4., 9., 1.],
        [8., 1., 6., 7., 2.],
        [6., 1., 4., 5., 3.]]), array([[0.],
        [8.],
        [4.],
        [2.]]), array([[7., 9., 5.],
        [9., 3., 9.],
        [9., 8., 4.],
        [5., 9., 3.]])]

In [57]:
np.vsplit(l,2) # vsplit makes split vertically.

[array([[0., 0., 7., 9., 4., 8., 8., 5., 0., 7., 9., 5.],
        [2., 0., 2., 3., 4., 4., 9., 1., 8., 9., 3., 9.]]),
 array([[4., 8., 2., 8., 1., 6., 7., 2., 4., 9., 8., 4.],
        [2., 3., 2., 6., 1., 4., 5., 3., 2., 5., 9., 3.]])]

In [58]:
np.vsplit(l,(1,3))

[array([[0., 0., 7., 9., 4., 8., 8., 5., 0., 7., 9., 5.]]),
 array([[2., 0., 2., 3., 4., 4., 9., 1., 8., 9., 3., 9.],
        [4., 8., 2., 8., 1., 6., 7., 2., 4., 9., 8., 4.]]),
 array([[2., 3., 2., 6., 1., 4., 5., 3., 2., 5., 9., 3.]])]

## Copies and Views:

In [59]:
e = np.arange(12)

In [60]:
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [61]:
f = e # Here, no new object got created. Both still point to the same object.

In [62]:
f is e

True

In [63]:
f.shape = 3,4

In [64]:
f.shape

(3, 4)

## View or Shallow Copy:

In [65]:
c = e.view() # It is a shallow copy.

In [66]:
print(c is e)

False


In [67]:
print(c.base is e)

True


In [68]:
c.shape = 2,6

In [69]:
e.shape

(3, 4)

In [70]:
d = e.copy() # It is a deep copy.

In [71]:
d is e

False

## Advanced Indexing:

In [72]:
w = np.arange(12)**2

In [73]:
print(w)

[  0   1   4   9  16  25  36  49  64  81 100 121]


In [74]:
i = np.array([1,1,3,8,5])

In [75]:
w[i]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [76]:
j = np.array([[3,4],[9,7]])

In [77]:
j

array([[3, 4],
       [9, 7]])

In [78]:
w[j]

array([[ 9, 16],
       [81, 49]], dtype=int32)

## Multi-dimensional arrays:

In [79]:
palette = np.array([[0,0,0],
                  [255,0,0],
                  [0,255,0],
                  [0,0,255],
                  [255,255,255]])

In [80]:
image = np.array([[0,1,2,0],
                 [0,3,4,0]])

In [81]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

## Multi-dimensional indexes:

In [82]:
k = np.arange(12).reshape(3,4)

In [83]:
k

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
 p = np.array([[0,1],
             [1,2]])

In [85]:
q = np.array([[2,1],
             [3,3]])

In [86]:
k[p,q]

array([[ 2,  5],
       [ 7, 11]])

In [87]:
ind1 = np.indices((5,3))

In [88]:
ind1

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [89]:
ind2 = np.indices((5,3,2))

In [90]:
ind2

array([[[[0, 0],
         [0, 0],
         [0, 0]],

        [[1, 1],
         [1, 1],
         [1, 1]],

        [[2, 2],
         [2, 2],
         [2, 2]],

        [[3, 3],
         [3, 3],
         [3, 3]],

        [[4, 4],
         [4, 4],
         [4, 4]]],


       [[[0, 0],
         [1, 1],
         [2, 2]],

        [[0, 0],
         [1, 1],
         [2, 2]],

        [[0, 0],
         [1, 1],
         [2, 2]],

        [[0, 0],
         [1, 1],
         [2, 2]],

        [[0, 0],
         [1, 1],
         [2, 2]]],


       [[[0, 1],
         [0, 1],
         [0, 1]],

        [[0, 1],
         [0, 1],
         [0, 1]],

        [[0, 1],
         [0, 1],
         [0, 1]],

        [[0, 1],
         [0, 1],
         [0, 1]],

        [[0, 1],
         [0, 1],
         [0, 1]]]])

In [91]:
iden1 = np.eye(5)

In [92]:
iden2 = np.identity(5)

In [93]:
iden1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [94]:
iden2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])