## NumPy practicals done from Fluidic Colours YouTube Channel.

In [1]:
import numpy as np

In [2]:
array1 = [[1,2,3],[4,5,6],[7,8,9]]

In [3]:
a1 = np.array(array1, dtype=np.float64)

In [4]:
a1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [5]:
a1.ndim

2

In [6]:
a1.size

9

In [7]:
a1.itemsize

8

In [8]:
a1.itemsize*a1.size

72

In [9]:
a1.dtype

dtype('float64')

In [10]:
a1.dtype.name

'float64'

In [11]:
print(type(a1))

<class 'numpy.ndarray'>


In [12]:
z = np.zeros((5,3), dtype=np.int64)

In [13]:
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [14]:
p = np.ones((5,3), dtype=np.float32)

In [15]:
p

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [16]:
e = np.empty((5,3), dtype=np.float32)

In [17]:
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [18]:
e1 = np.empty((5,3), dtype=np.float64)

In [19]:
e1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
z1 = np.random.uniform(-5,5,(5,3))

In [21]:
z1

array([[ 2.26940522e-03, -3.22119957e+00, -4.59498551e+00],
       [ 2.12513423e+00,  2.94296152e+00, -2.07157119e-01],
       [-3.87477929e+00, -2.40128446e+00, -8.00231944e-01],
       [-1.92319678e+00,  3.91010425e+00, -1.80449975e+00],
       [-1.81938452e+00, -6.82802542e-01, -2.33604408e+00]])

In [22]:
x1 = np.linspace(-10,10,201)

In [23]:
x1

array([-10. ,  -9.9,  -9.8,  -9.7,  -9.6,  -9.5,  -9.4,  -9.3,  -9.2,
        -9.1,  -9. ,  -8.9,  -8.8,  -8.7,  -8.6,  -8.5,  -8.4,  -8.3,
        -8.2,  -8.1,  -8. ,  -7.9,  -7.8,  -7.7,  -7.6,  -7.5,  -7.4,
        -7.3,  -7.2,  -7.1,  -7. ,  -6.9,  -6.8,  -6.7,  -6.6,  -6.5,
        -6.4,  -6.3,  -6.2,  -6.1,  -6. ,  -5.9,  -5.8,  -5.7,  -5.6,
        -5.5,  -5.4,  -5.3,  -5.2,  -5.1,  -5. ,  -4.9,  -4.8,  -4.7,
        -4.6,  -4.5,  -4.4,  -4.3,  -4.2,  -4.1,  -4. ,  -3.9,  -3.8,
        -3.7,  -3.6,  -3.5,  -3.4,  -3.3,  -3.2,  -3.1,  -3. ,  -2.9,
        -2.8,  -2.7,  -2.6,  -2.5,  -2.4,  -2.3,  -2.2,  -2.1,  -2. ,
        -1.9,  -1.8,  -1.7,  -1.6,  -1.5,  -1.4,  -1.3,  -1.2,  -1.1,
        -1. ,  -0.9,  -0.8,  -0.7,  -0.6,  -0.5,  -0.4,  -0.3,  -0.2,
        -0.1,   0. ,   0.1,   0.2,   0.3,   0.4,   0.5,   0.6,   0.7,
         0.8,   0.9,   1. ,   1.1,   1.2,   1.3,   1.4,   1.5,   1.6,
         1.7,   1.8,   1.9,   2. ,   2.1,   2.2,   2.3,   2.4,   2.5,
         2.6,   2.7,

In [24]:
x2 = np.arange(-10,10.05, 0.1)

In [25]:
x2

array([-1.00000000e+01, -9.90000000e+00, -9.80000000e+00, -9.70000000e+00,
       -9.60000000e+00, -9.50000000e+00, -9.40000000e+00, -9.30000000e+00,
       -9.20000000e+00, -9.10000000e+00, -9.00000000e+00, -8.90000000e+00,
       -8.80000000e+00, -8.70000000e+00, -8.60000000e+00, -8.50000000e+00,
       -8.40000000e+00, -8.30000000e+00, -8.20000000e+00, -8.10000000e+00,
       -8.00000000e+00, -7.90000000e+00, -7.80000000e+00, -7.70000000e+00,
       -7.60000000e+00, -7.50000000e+00, -7.40000000e+00, -7.30000000e+00,
       -7.20000000e+00, -7.10000000e+00, -7.00000000e+00, -6.90000000e+00,
       -6.80000000e+00, -6.70000000e+00, -6.60000000e+00, -6.50000000e+00,
       -6.40000000e+00, -6.30000000e+00, -6.20000000e+00, -6.10000000e+00,
       -6.00000000e+00, -5.90000000e+00, -5.80000000e+00, -5.70000000e+00,
       -5.60000000e+00, -5.50000000e+00, -5.40000000e+00, -5.30000000e+00,
       -5.20000000e+00, -5.10000000e+00, -5.00000000e+00, -4.90000000e+00,
       -4.80000000e+00, -

In [26]:
sine = np.sin(x1)

In [27]:
sine

array([ 0.54402111,  0.45753589,  0.36647913,  0.27176063,  0.17432678,
        0.07515112, -0.02477543, -0.12445442, -0.22288991, -0.31909836,
       -0.41211849, -0.50102086, -0.58491719, -0.66296923, -0.7343971 ,
       -0.79848711, -0.85459891, -0.90217183, -0.94073056, -0.96988981,
       -0.98935825, -0.99894134, -0.99854335, -0.98816823, -0.96791967,
       -0.93799998, -0.8987081 , -0.85043662, -0.79366786, -0.72896904,
       -0.6569866 , -0.57843976, -0.49411335, -0.40484992, -0.31154136,
       -0.21511999, -0.1165492 , -0.0168139 ,  0.0830894 ,  0.1821625 ,
        0.2794155 ,  0.37387666,  0.46460218,  0.55068554,  0.63126664,
        0.70554033,  0.77276449,  0.83226744,  0.88345466,  0.92581468,
        0.95892427,  0.98245261,  0.99616461,  0.99992326,  0.993691  ,
        0.97753012,  0.95160207,  0.91616594,  0.87157577,  0.81827711,
        0.7568025 ,  0.68776616,  0.61185789,  0.52983614,  0.44252044,
        0.35078323,  0.2555411 ,  0.15774569,  0.05837414, -0.04