## NumPy practicals done from Acadgild YouTube Channel.

NumPy stands for numerical Python. It is a foundational package for mathematical computing.

In [1]:
l = [1,2,3,4,5] # It is a Python list.

In [2]:
import numpy as np

In [3]:
np_arr = np.array(l)

In [4]:
np_arr

array([1, 2, 3, 4, 5])

In [5]:
type(np_arr)

numpy.ndarray

In [7]:
np.mat('1 2; 3 4; 5 6')

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [8]:
a = np.array([1,2,3,4])

In [9]:
a = np.array([1,2,3.0])
# Now, every element will get converted to float i.e. array([1., 2., 3.]). Typecasting is taking place.

Type precedence: Bool, Int, Float, String.

In [12]:
print(np.array([1,2,3], dtype=float))

[1. 2. 3.]


In [15]:
print(np.array([1,2,3], dtype='U'))

['1' '2' '3']


In [16]:
print(np.array([12354, 2, 3], dtype='<U2')) # It will limit output to two characters.

['12' '2' '3']


In [17]:
print(np.array([1,2,3], dtype=complex))

[1.+0.j 2.+0.j 3.+0.j]


In [18]:
x = np.array([('ABC', 26, 10000.0), ('XYZ', 31, 50000)], dtype=[('name','<U11'), ('age','int32'), ('salary','<f4')])
# we can also remove 11 from U11 and 4 from f4.

In [19]:
print('Row1', x[0])
print('Row2', x[1])

Row1 ('ABC', 26, 10000.)
Row2 ('XYZ', 31, 50000.)


## Some important points:
array_name.shape -- It will display shape of array (3,3)                                                               

array_name.size -- It will show total number of elements i.e. 9                                                      

array_name.dtype -- It will display data type of elements

array_name.ndim -- It will display dimension of array i.e. 2

In [22]:
three_arr = np.array([[[1,2,3],[4,5,6]],[[5,6,7],[6,7,8]]])

In [23]:
three_arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 6, 7],
        [6, 7, 8]]])