## NumPy practicals done from Fluidic Colours YouTube Channel.

In [1]:
import numpy as np

In [2]:
A = np.random.randint(0,5,(6))

In [3]:
A

array([0, 1, 3, 4, 3, 3])

In [4]:
B = np.random.randint(0,5,(6))

In [5]:
B

array([1, 4, 0, 4, 3, 1])

In [6]:
np.average(A, weights=B)

2.4615384615384617

In [7]:
np.average(A)

2.3333333333333335

In [8]:
mult = A*B

In [9]:
np.sum(mult)/np.sum(B)

2.4615384615384617

In [10]:
np.mean(A)

2.3333333333333335

In [11]:
np.vdot(A,B) # vdot gives dot product of two vectors.

32

In [12]:
np.median(A)

3.0

In [13]:
A.nonzero()
# it will output an array which will indexes of other array. Those indexes will be present where there is
# non-zero value.

(array([1, 2, 3, 4, 5], dtype=int64),)

In [14]:
np.inner(A,B)

32

In [15]:
np.outer(A,B)

array([[ 0,  0,  0,  0,  0,  0],
       [ 1,  4,  0,  4,  3,  1],
       [ 3, 12,  0, 12,  9,  3],
       [ 4, 16,  0, 16, 12,  4],
       [ 3, 12,  0, 12,  9,  3],
       [ 3, 12,  0, 12,  9,  3]])

In [16]:
# Details behind inner and outer remains to be explored.

In [17]:
C = np.outer(A,B)

In [18]:
CT = np.transpose(C)

In [19]:
CT

array([[ 0,  1,  3,  4,  3,  3],
       [ 0,  4, 12, 16, 12, 12],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  4, 12, 16, 12, 12],
       [ 0,  3,  9, 12,  9,  9],
       [ 0,  1,  3,  4,  3,  3]])

In [20]:
C.trace() # this function will add all the diagonal elements of a matrix.

32

In [21]:
A = np.array([4,0,2,4,4,3])

In [22]:
np.diff(A)
# This function will display an array with values obtained by subtracting the element of array passed with previous
# element in the same array.

array([-4,  2,  2,  0, -1])