## NumPy practicals done from Fluidic Colours YouTube Channel.

## Vector Operations:

In [1]:
import numpy as np

In [2]:
A = np.ones((5,3))

In [3]:
B = 5.0*np.ones((5,3))

In [4]:
C = np.random.randint(-5,5,(5,3))

In [5]:
A+B

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [6]:
A-B

array([[-4., -4., -4.],
       [-4., -4., -4.],
       [-4., -4., -4.],
       [-4., -4., -4.],
       [-4., -4., -4.]])

In [7]:
A*B

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [8]:
np.multiply(A,B)

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [9]:
A/B

array([[0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2]])

In [10]:
A1 = 1.5*A # Scalar multiplication i.e. each element of A will be multiplied by 1.5

In [11]:
A1

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]])

In [12]:
A1**B # each element of A1 got raised to the power of corresponding element in B.

array([[7.59375, 7.59375, 7.59375],
       [7.59375, 7.59375, 7.59375],
       [7.59375, 7.59375, 7.59375],
       [7.59375, 7.59375, 7.59375],
       [7.59375, 7.59375, 7.59375]])

In [13]:
A += B

In [14]:
A

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [15]:
A -= B

In [16]:
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
A *= B

In [18]:
A

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [19]:
A /= B

In [20]:
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
A **= B

In [22]:
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.sqrt(A)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.power(A, 0.2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
A**0.2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.exp(A)

array([[2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [27]:
np.exp(1)

2.718281828459045

In [28]:
np.exp(2)

7.38905609893065

np.dot(arr1, arr2) # if dimensions are compatible then multiplication will be done else ValueError.

To be explored: to do inverse of a matrix.

In [29]:
D = np.ones((5,5))

In [30]:
eigval, eigvec = np.linalg.eig(D)

In [31]:
eigval

array([5.00000000e+00, 5.65333918e-49, 0.00000000e+00, 0.00000000e+00,
       1.73014109e-64])

In [32]:
eigvec

array([[-4.47213595e-01,  1.13586253e-16,  1.13586253e-16,
         6.83745817e-32, -1.11062157e-16],
       [-4.47213595e-01,  8.66025404e-01,  8.66025404e-01,
         5.23461086e-16, -8.46780726e-01],
       [-4.47213595e-01, -2.88675135e-01, -2.88675135e-01,
        -7.93176298e-17,  1.11088069e-01],
       [-4.47213595e-01, -2.88675135e-01, -2.88675135e-01,
        -7.07106781e-01,  3.67846328e-01],
       [-4.47213595e-01, -2.88675135e-01, -2.88675135e-01,
         7.07106781e-01,  3.67846328e-01]])