## NumPy practicals done from Fluidic Colours YouTube Channel.

In [1]:
import numpy as np

In [2]:
x = np.linspace(0,10,11)

In [3]:
y = np.linspace(0,10,11)

In [4]:
xx,yy = np.meshgrid(x,y)

In [5]:
xx

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [6]:
yy

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In xx, we see that first row has been copied to all other rows whereas, in yy, first column has been copied to all other columns. So, we can generate this grid matrix without repitition even and the command is below:

In [7]:
xx,yy = np.meshgrid(x,y, sparse=True)

In earlier commands, sparse is by default set to False. After this, if we output xx and yy, it will only output one row and one column with retaining other 2-D characteristics.

In [8]:
xx

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [9]:
yy

array([[ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [10]:
ell = xx**2.0+yy*2.0

In [11]:
ell

array([[  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.],
       [  2.,   3.,   6.,  11.,  18.,  27.,  38.,  51.,  66.,  83., 102.],
       [  4.,   5.,   8.,  13.,  20.,  29.,  40.,  53.,  68.,  85., 104.],
       [  6.,   7.,  10.,  15.,  22.,  31.,  42.,  55.,  70.,  87., 106.],
       [  8.,   9.,  12.,  17.,  24.,  33.,  44.,  57.,  72.,  89., 108.],
       [ 10.,  11.,  14.,  19.,  26.,  35.,  46.,  59.,  74.,  91., 110.],
       [ 12.,  13.,  16.,  21.,  28.,  37.,  48.,  61.,  76.,  93., 112.],
       [ 14.,  15.,  18.,  23.,  30.,  39.,  50.,  63.,  78.,  95., 114.],
       [ 16.,  17.,  20.,  25.,  32.,  41.,  52.,  65.,  80.,  97., 116.],
       [ 18.,  19.,  22.,  27.,  34.,  43.,  54.,  67.,  82.,  99., 118.],
       [ 20.,  21.,  24.,  29.,  36.,  45.,  56.,  69.,  84., 101., 120.]])

Yet to be explored: mgrid, ogrid and sparse grid arrays.